version: '3'

services:
  poll:
    build: .
    restart: always
    ports:
      - 8000:8000/tcp
    environment:
      POLL__APPLICATION__DOMAIN: localhost
      POLL__APPLICATION__URL: http://localhost:8000
      POLL__COOKIE__SIGNING_KEY: zL8G258m3nUzqNmwEWThh6YEv7zgC6srqVdhm4c7EN8Sm5dGyr6S5963JfifDnvz
      POLL__DATABASE__HOST: mysql
      POLL__DATABASE__PORT: 3306
      POLL__DATABASE__USERNAME: admin
      POLL__DATABASE__PASSWORD: admin
      POLL__DATABASE__DATABASE: poll
      POLL__DATABASE__REQUIRE_SSL: false
      POLL__TRACING__JAEGER_ENDPOINT: jaeger:6831

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306/tcp
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: poll
      MYSQL_ROOT_PASSWORD: root

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686/tcp
      - 14268:14268/tcp

