application:
  domain: localhost
  flash_message_minimum_level: Debug
cookie:
  signing_key: zL8G258m3nUzqNmwEWThh6YEv7zgC6srqVdhm4c7EN8Sm5dGyr6S5963JfifDnvz
database:
  host: 127.0.0.1
  port: 5432
  username: admin
  password: admin
  database: poll
  require_ssl: false
tracing:
  log_level: debug
  jaeger_endpoint: localhost:6831
