name: Build

on:
  push:
    tags: 'dev-*'
    paths-ignore:
      - .github/**
      - docs/**
      - scripts/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: Setup toolchain
        uses: letung3105/poll.rs/.github/workflows/test.yaml@master

      - name: Run test suite
        uses: letung3105/poll.rs/.github/workflows/test.yaml@master

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive release binary
        uses: actions/upload-artifact@v3
        with:
          name: poll-x86_64-unknown-linux-gnu
          path: target/release/poll
