name: Build

on:
  push:
    tags: 'dev-*'
    paths-ignore:
      - .github/**
      - docs/**
      - scripts/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup toolchain
        uses: ./.github/actions/toolchain

      - name: Run test suite
        uses: ./.github/actions/test

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: release-binaries
          path: ./target/**/release/poll
