name: Build

on:
  push:
    tags: 'dev-*'
    paths-ignore:
      - .github/**
      - docs/**
      - scripts/**

jobs:
  test:
    uses: letung3105/poll.rs/.github/workflows/test.yaml@master

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive release binary
        uses: actions/upload-artifact@v3
        with:
          name: poll-x86_64-unknown-linux-gnu
          path: target/release/poll
