name: Continuous integration

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - .github/**
      - docs/**
      - scripts/**
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup toolchain
        uses: ./.github/actions/toolchain

      - name: Run test suite
        uses: ./.github/actions/test
