name: Continuous integration

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - .github/**
      - docs/**
      - scripts/**
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: Setup toolchain
        uses: letung3105/poll.rs/.github/workflows/test.yaml@master

      - name: Run test suite
        uses: letung3105/poll.rs/.github/workflows/test.yaml@master
