name: Continuous integration

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - .github/**
      - docs/**
      - scripts/**
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    uses: letung3105/poll.rs/.github/workflows/test.yaml@master
