name: Test
description: Check code quality and run the test suite
runs:
  using: composite
  steps:
    - name: Lint
      run: |
        cargo fmt --all -- --check
        cargo clippy --all

    - name: Install cargo check tools
      run: |
        cargo install --locked cargo-deny || true
        cargo install --locked cargo-outdated || true
        cargo install --locked cargo-audit || true
        cargo install --locked cargo-pants || true

    - name: Check
      run: |
        cargo deny check
        cargo outdated --exit-code 1
        rm -rf ~/.cargo/advisory-db
        cargo audit
        cargo pants

    - name: Test
      run: cargo test
